name: Build and Cache LLVM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/llvm-build
      INSTALL_DIR: /tmp/llvm-install

    steps:
      # 1. 检出代码（含子模块）
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential python3

      # 3. 配置缓存
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-llvm-${{ hashFiles('llvm-project/llvm/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-llvm-

      # 4. 构建 LLVM
      - name: Build LLVM
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.BUILD_DIR }} && cd ${{ env.BUILD_DIR }}
          cmake -G "Ninja" \
                -DCMAKE_BUILD_TYPE=Release \
                -DLLVM_ENABLE_PROJECTS="clang;lld" \
                -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
                ${{ github.workspace }}/llvm-project/llvm
          ninja install

      # 5. 打包产物
      - name: Archive Binaries
        run: |
          tar -czf llvm-bin.tar.gz -C ${{ env.INSTALL_DIR }} .

      # 6. 上传产物（使用最新 v4+）
      - uses: actions/upload-artifact@v4
        with:
          name: llvm-x86_64-bin
          path: llvm-bin.tar.gz
          retention-days: 7  # 自动清理旧产物（可选）
